apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: egress-checker
      app.kubernetes.io/component: egress-checker
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - podmonitor.yaml
