apiVersion: v1
kind: Service
metadata:
  name: egress-checker
spec:
  selector:
    app.kubernetes.io/name: egress-checker
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
